dist: trusty
sudo: required
language: node_js

node_js:
  - '6'

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g karma
  - npm install -g node-gyp

install:
  - npm install

before_script:
  - ng build

script:
  - karma start karma.conf.js --single-run
